
version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: myapp
    container_name: myapp
    restart: unless-stopped
    env_file: .env
    ports:
      - "$PORT:$PORT"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_DB=$DB_NAME
    ports:
      - "$DB_PORT:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
